### ISSUE TITLE
Docker ENV 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#83]
## Branch Core2

Docker Run Command 
https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers

### Docker Run
```
docker run --rm 
-e NG_ENVIRONMENT='staging' \ 
-e LANDMARK='http://informationcart.eastus2.cloudapp.azure.com:80/api/' \
-e MAPSAPI='http://informationcart.eastus2.cloudapp.azure.com:82/api/' \
--name coredatastore  -p 5000:5000  stuartshay/coredatastore
```

### Docker Compose 
https://github.com/stuartshay/CoreDataStore/blob/Core2/docker/docker-compose-staging.yml
(In Core2 Branch)

```
  web:
    container_name: 'coredatastore_web'
    image: "stuartshay/coredatastore:build"
    ports:
     - "5000:5000"
    environment:
     - NG_ENVIRONMENT=production
     - LANDMARK=http://LANDMARK.API:80/api/
    depends_on:
     - "database"
    networks:
- aspnetcoreapp-network
```

### Consul
https://www.consul.io/downloads_tools.html
